// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qyryykmpadguzxyiotur.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF5cnl5a21wYWRndXp4eWlvdHVyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2NTMzNDYsImV4cCI6MjA2ODIyOTM0Nn0.BojL2vbNEaZ4MU9qe504VG0mqXKvOeMzQuaG8WzCg9E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});